---
title: "Social Survey"
author: "Put your name here!"
date: "put the date here"
output:
  html_document: default
---

```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
source("Import_GSS2016_haven.R")
```
<!-- We recommend you use git branches -- create a separate branch for each major section i.e. Introduction, Methods, Results, Inferential Results, and Discussion and Conclusions - leave the YAML block untouched until the final merge where you put in your own name !-->

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->   

####This study deals with questions about possible relationships between views toward extramrital sex and sex, political views, and current relationship status. The data is from the 2016 general social survey.



# Sex

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

# Polyviews

<!--Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.!-->

# Relationship Status



# Discussion and Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variables causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->

we conclude that the data in some way is related to eachother. for example, we found out that a male was more likely to say extramarrigal sex was ok than a female was meaning a woman might value a relationship more than a male would. the biggest relations came with the political views. I have no knowledge in politics and dont know what a liberal or conservative is, but it seems liberals are a little more loose when it comes to relationships than conservatives who are very strict. when it comes to your curent relationship status, the reults are to be expected. single people are more likely to say extra marrigal sex is ok than a person who is currently in a relationship. My guess is that someone who is currently single doesnt value loyalty as much as someone who has a partner or spouse. i have gathered that your gender, political views, and your current relationship status all influence your opinion on extra marrigal sex.